In [1]:
# visualization and EDA
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style('whitegrid')

import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
# Define the models
from sklearn.linear_model import LogisticRegression
from sklearn import svm, tree
from sklearn.neighbors import KNeighborsClassifier
# Define model performance metrics 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, roc_auc_score, ConfusionMatrixDisplay


In [3]:
# Read the dataset into dataframe and display the first 5 rows
df = pd.read_csv('post natal data.csv')
# Drop the timestamp column
df.drop(columns='Timestamp', inplace=True)
df.dropna(inplace=True)
df.head()

Age Feeling sad or Tearful Irritable towards baby & partner  \
0  35-40                    Yes                              Yes   
1  40-45                    Yes                               No   
2  35-40                    Yes                               No   
3  35-40                    Yes                              Yes   
4  40-45                    Yes                               No   

  Trouble sleeping at night Problems concentrating or making decision  \
0   Two or more days a week                                       Yes   
1                        No                                       Yes   
2                       Yes                                       Yes   
3                       Yes                                       Yes   
4   Two or more days a week                                       Yes   

  Overeating or loss of appetite Feeling anxious Feeling of guilt  \
0                            Yes             Yes               No   
1                            Yes              No              Yes   
2                            Yes             Yes               No   
3                             No             Yes            Maybe   
4                             No             Yes               No   

  Problems of bonding with baby Suicide attempt  
0                           Yes             Yes  
1                           Yes              No  
2                     Sometimes              No  
3                            No              No  
4                           Yes              No

In [4]:
le = LabelEncoder()

# Apply LabelEncoder to categorical columns
df_le = df.copy()
for column in df.columns[1:]:
    df_le[column] = le.fit_transform(df[column])

df_le.head()

Age  Feeling sad or Tearful  Irritable towards baby & partner  \
0  35-40                       2                                 2   
1  40-45                       2                                 0   
2  35-40                       2                                 0   
3  35-40                       2                                 2   
4  40-45                       2                                 0   

   Trouble sleeping at night  Problems concentrating or making decision  \
0                          1                                          2   
1                          0                                          2   
2                          2                                          2   
3                          2                                          2   
4                          1                                          2   

   Overeating or loss of appetite  Feeling anxious  Feeling of guilt  \
0                               2                1                 1   
1                               2                0                 2   
2                               2                1                 1   
3                               0                1                 0   
4                               0                1                 1   

   Problems of bonding with baby  Suicide attempt  
0                              2                2  
1                              2                0  
2                              1                0  
3                              0                0  
4                              2                0

In [5]:
le.classes_

array(['No', 'Not interested to say', 'Yes'], dtype=object)

In [6]:
# Convert Age range to midpoint of the range
age_mapping = {"25-30":27.5,"35-40": 37.5, "40-45": 42.5, "30-35": 32.5,"45-50":47.5}
df_le["Age"] = df["Age"].map(age_mapping)

df_le.head(2)

Age  Feeling sad or Tearful  Irritable towards baby & partner  \
0  37.5                       2                                 2   
1  42.5                       2                                 0   

   Trouble sleeping at night  Problems concentrating or making decision  \
0                          1                                          2   
1                          0                                          2   

   Overeating or loss of appetite  Feeling anxious  Feeling of guilt  \
0                               2                1                 1   
1                               2                0                 2   

   Problems of bonding with baby  Suicide attempt  
0                              2                2  
1                              2                0

In [7]:
# let define feature columns
features = ["Age", "Feeling sad or Tearful", "Irritable towards baby & partner", 
            "Trouble sleeping at night", "Problems concentrating or making decision", 
            "Overeating or loss of appetite", "Feeling of guilt", 
            "Problems of bonding with baby", "Suicide attempt"]

# Define target column
target = "Feeling anxious"

In [8]:
# le = LabelEncoder()
# df_le[features] = df_le[features].apply(le.fit_transform)

In [9]:
df_le[df_le["Feeling anxious"]== 0][:3]

Age  Feeling sad or Tearful  Irritable towards baby & partner  \
1   42.5                       2                                 0   
8   37.5                       2                                 2   
10  32.5                       2                                 1   

    Trouble sleeping at night  Problems concentrating or making decision  \
1                           0                                          2   
8                           0                                          2   
10                          1                                          0   

    Overeating or loss of appetite  Feeling anxious  Feeling of guilt  \
1                                2                0                 2   
8                                0                0                 1   
10                               2                0                 2   

    Problems of bonding with baby  Suicide attempt  
1                               2                0  
8                               0                2  
10                              0                0

In [10]:
Xdf = df_le.drop(columns=target).values
y= df_le[target].values

In [11]:
len(Xdf), len(y)

(1491, 1491)

In [12]:
Xdf[:3]

array([[37.5,  2. ,  2. ,  1. ,  2. ,  2. ,  1. ,  2. ,  2. ],
       [42.5,  2. ,  0. ,  0. ,  2. ,  2. ,  2. ,  2. ,  0. ],
       [37.5,  2. ,  0. ,  2. ,  2. ,  2. ,  1. ,  1. ,  0. ]])

In [13]:
# Split the data into training set and test set
X_train, X_test, y_train, y_test = train_test_split(Xdf, y, test_size=0.2, random_state=32)

In [14]:
param = {'n_neighbors': 10, 'p': 1, 'weights': 'distance'}
knn_clf = KNeighborsClassifier(**param)

In [15]:
dt_clf = tree.DecisionTreeClassifier(random_state=42)

In [16]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [17]:
dt_clf.score(X_train, y_train)

1.0

In [18]:
dt_clf.score(X_test, y_test)

1.0

In [19]:
X_test[:2]

array([[47.5,  1. ,  2. ,  1. ,  2. ,  1. ,  0. ,  2. ,  1. ],
       [37.5,  2. ,  0. ,  2. ,  0. ,  1. ,  1. ,  0. ,  0. ]])

In [22]:
#saving the model
import pickle 
with open("dtmodel.pkl", "wb") as f:
    pickle.dump(dt_clf, f)

In [23]:
#loading the model
with open("dtmodel.pkl", "rb") as f:
    model= pickle.load(f)

In [24]:
type(model)

sklearn.tree._classes.DecisionTreeClassifier

In [25]:
Xdf[3]

array([37.5,  2. ,  2. ,  2. ,  2. ,  0. ,  0. ,  0. ,  0. ])

In [26]:
import numpy as np
test = np.array([4, 1, 2, 1, 2, 1, 0, 2, 1]).reshape(1, -1)
test2 = np.array([2, 2, 0, 2, 0,1,1,0,0]).reshape(1, -1)
test3= np.array([37,  2,  2,  2,  2,  0,  0,  0,  0]).reshape(1,-1)

In [27]:
model.predict(test)[0], model.predict(test3)[0]

(1, 1)

In [28]:
y_test[:3]

array([1, 0, 1])

In [29]:
y_preds = knn_clf.predict(X_test)

acc = accuracy_score(y_test, y_preds)

print(f"Model accuracy on test set: {round(acc,2)}")

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
# @st.cache_data
# def get_img_as_base64(file):
#     with open(file, "rb") as f:
#         data = f.read()
#     return base64.b64encode(data).decode()


# img = get_img_as_base64("C:/Users/Techa/Desktop/2023leave/mlflow/dsn/image.png")




# [data-testid="stSidebar"] > div:first-child {{
# background-image: url("data:image/png;base64,{img}");
# background-position: center; 
# background-repeat: no-repeat;
# background-attachment: fixed;
# }}




: 